import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { getPackages } from '../tinycld.packages'
import { loadManifest, resolvePackageDir } from './generate-packages'

const __filename = fileURLToPath(import.meta.url)
const ROOT = process.env.TINYCLD_APP_ROOT
    ? path.resolve(process.env.TINYCLD_APP_ROOT)
    : path.resolve(path.dirname(__filename), '..')

export interface ConfigSettingsPanel {
    slug: string
    label: string
    component: string // subpath, e.g. 'settings/provider'
}

export interface ConfigPkg {
    packageName: string
    slug: string
    schemaType: string // e.g. 'ContactsSchema'; '' for settings-only
    hasRegister: boolean
    hasSidebar: boolean
    hasProvider: boolean
    hasSeed: boolean
    settings: ConfigSettingsPanel[]
    manifest: { name: string; slug: string; version: string; description: string } & Record<
        string,
        unknown
    >
}

function ident(slug: string): string {
    // 'google-takeout-import' -> 'googleTakeoutImport'
    return slug.replace(/-([a-z])/g, (_m, c) => c.toUpperCase())
}

function pascal(slug: string): string {
    const camel = ident(slug)
    return camel.charAt(0).toUpperCase() + camel.slice(1)
}

function jsonLiteral(value: unknown): string {
    // Manifest values are plain JSON-serializable objects/arrays/strings.
    return JSON.stringify(value)
}

/**
 * Build the source text of tinycld.config.ts from a description of each linked
 * package's contributions. Pure + deterministic so it can be unit-tested
 * without touching disk.
 */
export function buildConfigSource(pkgs: ConfigPkg[]): string {
    const lines: string[] = ['// Auto-generated by scripts/generate-config.ts — do not edit']
    lines.push("import { definePackageEntry } from '@tinycld/core/lib/packages/config-types'")

    const needsLazy = pkgs.some(p => p.hasSidebar || p.settings.length > 0)
    if (needsLazy) lines.push("import { lazy } from 'react'")

    // value + type imports per package
    for (const p of pkgs) {
        if (p.hasRegister) {
            lines.push(
                `import { registerCollections as ${ident(p.slug)}Register } from '${p.packageName}/collections'`
            )
            lines.push(`import type { ${p.schemaType} } from '${p.packageName}/types'`)
        }
        if (p.hasProvider) {
            lines.push(`import ${ident(p.slug)}Provider from '${p.packageName}/provider'`)
        }
        // NOTE: seeds are deliberately NOT imported here. Seed modules are
        // dev/seed-time-only (they use Node `import.meta.dirname`, fs reads,
        // etc.) and must never enter the app bundle — Hermes can't parse
        // `import.meta`. They're emitted into a separate Node-only
        // tinycld.seeds.ts that the seed runner imports. See buildSeedsSource.
    }

    lines.push('')
    lines.push('export const tinycldConfig = [')
    for (const p of pkgs) {
        const schemaParam = p.hasRegister ? p.schemaType : 'Record<string, never>'
        lines.push(`    definePackageEntry<${schemaParam}>()({`)
        lines.push(
            `        manifest: { ...(${jsonLiteral(p.manifest)} as const), packageName: ${jsonLiteral(p.packageName)} },`
        )
        if (p.hasRegister) lines.push(`        registerCollections: ${ident(p.slug)}Register,`)
        if (p.hasSidebar) {
            lines.push(`        sidebar: lazy(() => import('${p.packageName}/sidebar')),`)
        }
        if (p.hasProvider) lines.push(`        provider: ${ident(p.slug)}Provider,`)
        if (p.settings.length > 0) {
            lines.push('        settings: [')
            for (const s of p.settings) {
                lines.push(
                    `            { slug: ${jsonLiteral(s.slug)}, label: ${jsonLiteral(s.label)}, Component: lazy(() => import('${p.packageName}/${s.component}')) },`
                )
            }
            lines.push('        ],')
        }
        lines.push('    }),')
    }
    lines.push('] as const')
    lines.push('')

    // Emit MergedPackageSchema as a LITERAL intersection of each package's
    // schema type (like the old generated package-collections.ts did). This is
    // pure types — it must NOT derive from `typeof tinycldConfig` (the values),
    // because pocketbase's coreStores depends on createCollection<MergedSchema>,
    // and a value-derived schema would close a circular type reference
    // (TS2456). Importing this precomputed type breaks the cycle.
    // The schema type names are already imported above (with the entries). The
    // union below reuses those same imported names.
    const withSchema = pkgs.filter(p => p.hasRegister)
    const intersection =
        withSchema.length > 0
            ? withSchema.map(p => p.schemaType).join(' & ')
            : 'Record<string, never>'
    lines.push(`export type MergedPackageSchema = ${intersection}`)
    lines.push('')
    return lines.join('\n')
}

/**
 * Build the source of tinycld.seeds.ts — a Node-only module the seed runner
 * imports. Seeds live here (NOT in tinycld.config.ts) because seed modules use
 * Node-only APIs (`import.meta.dirname`, fs) that can't enter the app bundle.
 * Each entry carries the seed fn plus the slug/dependencies that deriveSeeds
 * needs to order them.
 */
export function buildSeedsSource(pkgs: ConfigPkg[]): string {
    const withSeeds = pkgs.filter(p => p.hasSeed)
    const lines: string[] = ['// Auto-generated by scripts/generate-config.ts — do not edit']
    for (const p of withSeeds) {
        lines.push(`import ${ident(p.slug)}Seed from '${p.packageName}/seed'`)
    }
    lines.push('')
    lines.push('export const tinycldSeeds = [')
    for (const p of withSeeds) {
        const deps = (p.manifest.dependencies as string[] | undefined) ?? []
        const depsLiteral = deps.length > 0 ? jsonLiteral(deps) : '[]'
        lines.push(
            `    { manifest: { slug: ${jsonLiteral(p.slug)}, dependencies: ${depsLiteral} }, seed: ${ident(p.slug)}Seed },`
        )
    }
    lines.push('] as const')
    lines.push('')
    return lines.join('\n')
}

/** Detect which contributions a package declares, reading its manifest + dir. */
function describePackage(packageName: string): ConfigPkg | null {
    if (packageName === '@tinycld/core') return null // core is wired in explicitly, not a feature entry
    const dir = resolvePackageDir(packageName)
    const manifest = loadManifest(dir) as ConfigPkg['manifest'] & {
        collections?: { register: string; types: string }
        sidebar?: { component: string }
        provider?: { component: string }
        seed?: { script: string }
        settings?: ConfigSettingsPanel[]
    }
    const slug = manifest.slug
    const hasRegister = Boolean(manifest.collections?.register)
    return {
        packageName,
        slug,
        schemaType: hasRegister ? `${pascal(slug)}Schema` : '',
        hasRegister,
        hasSidebar: Boolean(manifest.sidebar?.component),
        hasProvider: Boolean(manifest.provider?.component),
        hasSeed: Boolean(manifest.seed?.script),
        settings: manifest.settings ?? [],
        manifest: {
            name: manifest.name,
            slug: manifest.slug,
            version: manifest.version,
            description: manifest.description,
            ...(manifest.nav ? { nav: manifest.nav } : {}),
            ...(manifest.routes ? { routes: manifest.routes } : {}),
            ...(manifest.publicRoutes ? { publicRoutes: manifest.publicRoutes } : {}),
            ...(manifest.dependencies ? { dependencies: manifest.dependencies } : {}),
        },
    }
}

function collectPkgs(): ConfigPkg[] {
    const out: ConfigPkg[] = []
    for (const name of getPackages()) {
        const desc = describePackage(name)
        if (desc) out.push(desc)
    }
    // stable order by slug for deterministic output
    out.sort((a, b) => a.slug.localeCompare(b.slug))
    return out
}

export function writeConfig(): void {
    const pkgs = collectPkgs()
    const configPath = path.join(ROOT, 'tinycld.config.ts')
    fs.writeFileSync(configPath, buildConfigSource(pkgs))

    // Seeds go in a SEPARATE Node-only module — they use import.meta/fs and must
    // not enter the app bundle. The seed runner imports tinycld.seeds.ts.
    fs.writeFileSync(path.join(ROOT, 'tinycld.seeds.ts'), buildSeedsSource(pkgs))

    // Re-export through the @tinycld/app-generated/* alias so core can import it
    // as @tinycld/app-generated/tinycld-config (Metro/Vitest both alias
    // app-generated/* → lib/generated/*).
    const generatedDir = process.env.TINYCLD_GENERATED_DIR
        ? path.resolve(process.env.TINYCLD_GENERATED_DIR)
        : path.join(ROOT, 'lib', 'generated')
    fs.mkdirSync(generatedDir, { recursive: true })
    fs.writeFileSync(
        path.join(generatedDir, 'tinycld-config.ts'),
        '// Auto-generated by scripts/generate-config.ts — do not edit\n' +
            "export { tinycldConfig } from '../../tinycld.config'\n" +
            "export type { MergedPackageSchema } from '../../tinycld.config'\n"
    )
    // Note: tinycld.config.ts is gitignored generated output (like everything in
    // lib/generated/), so biome never lints it — no formatting pass needed. The
    // emitted JSON-literal manifests are valid TS regardless of quote style.
}

function isMainModule(): boolean {
    if ((import.meta as { main?: boolean }).main) return true
    if (!process.argv[1]) return false
    try {
        return fs.realpathSync(process.argv[1]) === fs.realpathSync(__filename)
    } catch {
        return false
    }
}

if (isMainModule()) {
    writeConfig()
    console.log('Wrote tinycld.config.ts')
}
